// Generated by CoffeeScript 1.9.2
var contents, dir, file, files, fs, i, len, parse, path, results;

parse = require('./parse');

path = require('path');

fs = require('fs');

dir = path.join(process.cwd(), 'glossary');

files = fs.readdirSync(dir);

results = {};

for (i = 0, len = files.length; i < len; i++) {
  file = files[i];
  if (file.substr(-3) !== '.md') {
    continue;
  }
  contents = fs.readFileSync(path.join(dir, file), 'utf8');
  contents = parse(contents);
  results[file] = contents.meta;
}

fs.writeFileSync('catalog.json', JSON.stringify(results, null, 2));
