// Generated by CoffeeScript 1.9.2
var contents, dir, file, files, fs, i, len, parse, path, results;

parse = require('./parse');

path = require('path');

fs = require('fs');

dir = path.join(process.cwd(), 'glossary');

files = fs.readdirSync(dir);

results = [];

for (i = 0, len = files.length; i < len; i++) {
  file = files[i];
  if (file.substr(-3) !== '.md') {
    continue;
  }
  if (file === 'index.md') {
    continue;
  }
  contents = fs.readFileSync(path.join(dir, file), 'utf8');
  contents = parse(contents);
  contents.meta.filename = file.slice(0, -3);
  results.push(contents.meta);
}

results.sort(function(a, b) {
  if (a.filename < b.filename) {
    return -1;
  }
  if (a.filename > b.filename) {
    return 1;
  }
  return 0;
});

fs.writeFileSync('catalog.json', JSON.stringify(results, null, 2));
