// Generated by CoffeeScript 1.9.2
var component, dom, exe, hub, katex, kramed, odoql, ref, relay, renderrichtext, root, router, scene, widget;

ref = require('odojs'), component = ref.component, widget = ref.widget, hub = ref.hub, dom = ref.dom;

relay = require('odo-relay');

exe = require('odoql-exe');

odoql = require('odoql/odojs');

component.use(odoql);

hub = hub();

exe = exe({
  hub: hub
});

katex = require('katex');

kramed = require('kramed');

renderrichtext = widget({
  render: function(state, params) {
    return dom('div');
  },
  afterMount: function(el, state, params) {
    var eq, equation, equations, i, len, results;
    el.innerHTML = kramed(params);
    equations = document.querySelectorAll('script[type^=math]');
    results = [];
    for (i = 0, len = equations.length; i < len; i++) {
      equation = equations[i];
      eq = document.createElement('span');
      equation.parentNode.insertBefore(eq, equation);
      katex.render(equation.innerHTML, eq);
      results.push(equation.parentNode.removeChild(equation));
    }
    return results;
  },
  onUpdate: function(el, state, params) {
    return el.innerHTML = kramed(params);
  }
});

router = component({
  render: function(state, params, hub) {
    if (params.autocomplete == null) {
      params.autocomplete = {};
    }
    return dom('#root.container', [renderrichtext(null, "# I am using __markdown__\n\n- One\n- Two\n- Three $$c = \\pm\\sqrt{a^2 + b^2}$$\n\n$$\n\\int_0^\\infty e^{-x^2} dx=\\frac{\\sqrt{\\pi}}{2}\n$$\n")]);
  }
});

root = document.querySelector('#root');

scene = relay(root, router, exe, {
  hub: hub
});

hub.every('update', function(p, cb) {
  scene.update(p);
  return cb();
});

scene.update({});
